version: 0.2
env:
  variables:
    IMG: "app"
    REPO: "184665364105.dkr.ecr.us-east-1.amazonaws.com/app:"      
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --region us-east-1)
      - TAG="$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 8)"
  build:
    commands:
      - docker build -tag "${IMG}:${TAG}"
      - docker tag "${IMG}:${TAG}" "${REPO}":${TAG} 
  post_build:
    commands:
      - docker push "${REPO}:${TAG}"
      - printf '{"Image":"%s:%s"}' $REPO $TAG > build.json
artifacts:
  files: build.json
  discard-paths: yes